Block reward address and Conversion rate between space pledged and solution range
subspace/protocol-specs pull request #28
Opened 2024-05-07 07:16 UTC by xm0onh

This PR consists of two paragraphs:
1. Describing the Block Reward Address on the Consensus chain page.
2. Conversion rate between solution range and space pledged (#13 )

2024-05-07 08:47 UTC, dariolina requested changes

2024-05-07 08:47 UTC, dariolina commented on docs/consensus/consensus_chain.md
> ++    pub reward_address: AccountId,
```suggestion
    /// Address for receiving block reward
    pub reward_address: AccountId,
```

2024-05-07 08:47 UTC, dariolina commented on docs/consensus/consensus_chain.md
> +    pub encoding: Piece,
Actually these `struct` fields are outdated. In the `proof_of_archival_storage.md` spec somewhere there should be the new one. Or double-check it with the codebase directly.

2024-05-07 08:47 UTC, dariolina commented on docs/consensus/consensus_chain.md
> +In the current blockchain farming setup, a farmer’s identity is used for plot creation, block signing, and receiving block rewards, posing risks like plot invalidation on testnet when used across mul
```suggestion
In a basic blockchain farming setup, a farmer’s identity would be used for plot creation, block signing, and receiving block rewards, posing risks like plot invalidation on testnet when used across multiple nodes and incompatibility with cold wallets. To address these,  the farmer's identity is decoupled from the reward address by introducing a `--reward-address` argument in the farmer app, allowing the specification of a separate address for block rewards. This  additional `reward_address` block header field, enhances security, supports multi-replica farming, and aligns farming operations with practices in PoW mining where reward addresses are independent of operational identities.
```

2024-05-07 16:57 UTC, xm0onh commented
Thanks!
I made the changes and added the updated struct from the subspace repo: https://github.com/subspace/subspace/blob/f8bf2809a565d3044623838a08e7417eade95168/crates/subspace-core-primitives/src/lib.rs#L603

2024-05-13 08:45 UTC, dariolina approved these changes

2024-05-13 08:45 UTC, merged