Update staking withdraw
subspace/protocol-specs pull request #46
Opened 2024-09-10 09:00 UTC by NingLin-P

The changes are implemented in https://github.com/autonomys/subspace/pull/2993

2024-09-17 10:07 UTC, dariolina requested changes

2024-09-17 10:07 UTC, dariolina commented on docs/decex/staking.md
> + If the stake after withdrawing below the operator's `minimum_nominator_stake`, the nominator is completely unstaked, however the operator cannot withdraw below the `MinOperatorStake`.
```suggestion
 If the nominator's stake after withdrawal results below the operator's required `minimum_nominator_stake,` the nominator is automatically completely unstacked. Contrary, the operator cannot withdraw below the `MinOperatorStake`.
```

2024-09-17 16:54 UTC, NingLin-P commented
Interesting, I tried to push the change to this PR but it seems my account lack of permission now...
```
ERROR: Permission to subspace/protocol-specs.git denied to NingLin-P.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

2024-09-19 08:24 UTC, dariolina approved these changes

2024-09-19 09:48 UTC, merged